// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260718135143_PreventDuplicateWorldParticipationAndCityCoordinates")]
    partial class PreventDuplicateWorldParticipationAndCityCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllianceAlliance", b =>
                {
                    b.Property<Guid>("AlliancesAtWarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlliancesPactedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlliancesAtWarId", "AlliancesPactedId");

                    b.HasIndex("AlliancesPactedId");

                    b.ToTable("AllianceAlliance");
                });

            modelBuilder.Entity("Domain.Entities.Alliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BannerImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Name");

                    b.ToTable("Alliances");
                });

            modelBuilder.Entity("Domain.Entities.AllianceInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByWorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvitedWorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByWorldPlayerId");

                    b.HasIndex("InvitedWorldPlayerId");

                    b.HasIndex("AllianceId", "InvitedWorldPlayerId");

                    b.ToTable("AllianceInvitations");
                });

            modelBuilder.Entity("Domain.Entities.AllianceRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllianceIdA")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllianceIdB")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorAllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RespondingAllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AllianceIdB");

                    b.HasIndex("WorldId");

                    b.HasIndex("AllianceIdA", "AllianceIdB", "RelationType", "Status");

                    b.ToTable("AllianceRelations", t =>
                        {
                            t.HasCheckConstraint("CK_AllianceRelations_DifferentAlliances", "[AllianceIdA] <> [AllianceIdB]");
                        });
                });

            modelBuilder.Entity("Domain.Entities.BattleReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppliedModifiersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttackerLossesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefenderLossesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<string>("RevivedUnitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BattleReports");
                });

            modelBuilder.Entity("Domain.Entities.BugReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("BugReports");
                });

            modelBuilder.Entity("Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeOfUpgradeFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOfUpgradeStarted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNPC")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastExoticResourceUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastResistanceUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Metal")
                        .HasColumnType("float");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<double>("Resistance")
                        .HasColumnType("float");

                    b.Property<double>("ResistanceTarget")
                        .HasColumnType("float");

                    b.Property<double>("Stone")
                        .HasColumnType("float");

                    b.Property<double>("Wood")
                        .HasColumnType("float");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldPlayerId");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_World_Coordinates");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.CityExoticResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "ResourceType")
                        .IsUnique()
                        .HasDatabaseName("IX_CityExoticResources_City_Type");

                    b.ToTable("CityExoticResources");
                });

            modelBuilder.Entity("Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldPlayerId");

                    b.HasIndex("ConversationId", "WorldPlayerId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("Domain.Entities.DailyObjectiveAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DailyObjectiveSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<double>("Target")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DailyObjectiveSetId", "DefinitionId")
                        .IsUnique();

                    b.HasIndex("DailyObjectiveSetId", "Slot")
                        .IsUnique();

                    b.ToTable("DailyObjectiveAssignments");
                });

            modelBuilder.Entity("Domain.Entities.DailyObjectiveSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DayStartUtc")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldPlayerId")
                        .IsUnique();

                    b.ToTable("DailyObjectiveSets");
                });

            modelBuilder.Entity("Domain.Entities.IdeologyFocus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeOfIdeologyFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOfIdeologyStarted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("IdeologyFocuses");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Research", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ResearchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldPlayerId");

                    b.ToTable("Researches");
                });

            modelBuilder.Entity("Domain.Entities.UnitDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LegEndX")
                        .HasColumnType("int");

                    b.Property<int>("LegEndY")
                        .HasColumnType("int");

                    b.Property<int>("LegStartX")
                        .HasColumnType("int");

                    b.Property<int>("LegStartY")
                        .HasColumnType("int");

                    b.Property<double>("LootMetal")
                        .HasColumnType("float");

                    b.Property<double>("LootStone")
                        .HasColumnType("float");

                    b.Property<double>("LootWood")
                        .HasColumnType("float");

                    b.Property<int>("Mobility")
                        .HasColumnType("int");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StationedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("TargetCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UnitDeploymentMovementStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("IX_UnitDeployments_WorldId");

                    b.HasIndex("WorldPlayerId");

                    b.HasIndex("Phase", "UnitDeploymentMovementStatus", "ArrivalTime")
                        .HasDatabaseName("IX_UnitDeployments_DueMovement");

                    b.HasIndex("TargetCityId", "Type", "Phase")
                        .HasDatabaseName("IX_UnitDeployments_TargetSupport");

                    b.ToTable("UnitDeployments");
                });

            modelBuilder.Entity("Domain.Entities.UnitStack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UnitDeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UnitDeploymentId");

                    b.HasIndex("WorldPlayerId");

                    b.ToTable("UnitStacks");
                });

            modelBuilder.Entity("Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MapSeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("World");
                });

            modelBuilder.Entity("Domain.Entities.WorldIsland", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellX")
                        .HasColumnType("int");

                    b.Property<int>("CellY")
                        .HasColumnType("int");

                    b.Property<int>("CenterX")
                        .HasColumnType("int");

                    b.Property<int>("CenterY")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<float>("EdgeRoughness")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("MajorRadius")
                        .HasColumnType("real");

                    b.Property<float>("MinorRadius")
                        .HasColumnType("real");

                    b.Property<float>("RotationDegrees")
                        .HasColumnType("real");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "CellX", "CellY")
                        .IsUnique()
                        .HasDatabaseName("IX_WorldIslands_World_Cell");

                    b.ToTable("WorldIslands");
                });

            modelBuilder.Entity("Domain.Entities.WorldIslandExoticResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CoinInvestment")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MetalInvestment")
                        .HasColumnType("float");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.Property<double>("StoneInvestment")
                        .HasColumnType("float");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<double>("WoodInvestment")
                        .HasColumnType("float");

                    b.Property<Guid>("WorldIslandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldIslandId", "ResourceType")
                        .IsUnique()
                        .HasDatabaseName("IX_WorldIslandExoticResources_Island_Type");

                    b.HasIndex("WorldIslandId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_WorldIslandExoticResources_Island_Slot");

                    b.ToTable("WorldIslandExoticResources");
                });

            modelBuilder.Entity("Domain.Entities.WorldMapObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ReferenceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("X")
                        .HasColumnType("smallint");

                    b.Property<short>("Y")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "X", "Y", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_WorldMapObjects_World_Coordinates_Type");

                    b.ToTable("WorldMapObjects");
                });

            modelBuilder.Entity("Domain.User.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Domain.User.WorldPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllianceRole")
                        .HasColumnType("int");

                    b.Property<double>("Coins")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ideology")
                        .HasColumnType("int");

                    b.Property<double>("IdeologyFocusPoints")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ResearchPoints")
                        .HasColumnType("float");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("WorldId");

                    b.HasIndex("PlayerProfileId", "WorldId")
                        .IsUnique()
                        .HasDatabaseName("UX_WorldPlayers_Profile_World");

                    b.ToTable("WorldPlayers");
                });

            modelBuilder.Entity("Domain.Workers.Abstraction.BaseJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid>("WorldPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted", "ExecutionTime")
                        .HasDatabaseName("IX_Jobs_Due");

                    b.ToTable("Jobs");

                    b.HasDiscriminator<string>("JobType").HasValue("BaseJob");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Workers.BuildingJob", b =>
                {
                    b.HasBaseType("Domain.Workers.Abstraction.BaseJob");

                    b.Property<int>("BuildingType")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("int");

                    b.HasIndex("CityId");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("Domain.Workers.RecruitmentJob", b =>
                {
                    b.HasBaseType("Domain.Workers.Abstraction.BaseJob");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastTickTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("SecondsPerUnit")
                        .HasColumnType("float");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.ToTable("Jobs", t =>
                        {
                            t.Property("CityId")
                                .HasColumnName("RecruitmentJob_CityId");
                        });

                    b.HasDiscriminator().HasValue("RecruitmentSpeed");
                });

            modelBuilder.Entity("Domain.Workers.ResearchJob", b =>
                {
                    b.HasBaseType("Domain.Workers.Abstraction.BaseJob");

                    b.Property<string>("ResearchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Research");
                });

            modelBuilder.Entity("AllianceAlliance", b =>
                {
                    b.HasOne("Domain.Entities.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AlliancesAtWarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AlliancesPactedId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Alliance", b =>
                {
                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AllianceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AppliesToCategory")
                                .HasColumnType("int");

                            b1.Property<bool>("ExcludeElite")
                                .HasColumnType("bit");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Tag")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("AllianceId");

                            b1.ToTable("AllianceModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AllianceId");
                        });

                    b.Navigation("ModifiersInternal");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.Entities.AllianceInvitation", b =>
                {
                    b.HasOne("Domain.Entities.Alliance", "Alliance")
                        .WithMany()
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User.WorldPlayer", "InvitedByWorldPlayer")
                        .WithMany()
                        .HasForeignKey("InvitedByWorldPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User.WorldPlayer", "InvitedWorldPlayer")
                        .WithMany()
                        .HasForeignKey("InvitedWorldPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alliance");

                    b.Navigation("InvitedByWorldPlayer");

                    b.Navigation("InvitedWorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.AllianceRelation", b =>
                {
                    b.HasOne("Domain.Entities.Alliance", "AllianceA")
                        .WithMany("RelationsAsAllianceA")
                        .HasForeignKey("AllianceIdA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Alliance", "AllianceB")
                        .WithMany("RelationsAsAllianceB")
                        .HasForeignKey("AllianceIdB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllianceA");

                    b.Navigation("AllianceB");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.Entities.BugReport", b =>
                {
                    b.HasOne("Domain.User.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Domain.Entities.Building", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Buildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User.WorldPlayer", "WorldPlayer")
                        .WithMany("Cities")
                        .HasForeignKey("WorldPlayerId");

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AppliesToCategory")
                                .HasColumnType("int");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("ExcludeElite")
                                .HasColumnType("bit");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Tag")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("CityId");

                            b1.ToTable("CityModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("ModifiersInternal");

                    b.Navigation("World");

                    b.Navigation("WorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.CityExoticResource", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("ExoticResources")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User.WorldPlayer", "WorldPlayer")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("WorldPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("WorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.DailyObjectiveAssignment", b =>
                {
                    b.HasOne("Domain.Entities.DailyObjectiveSet", "DailyObjectiveSet")
                        .WithMany("Assignments")
                        .HasForeignKey("DailyObjectiveSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyObjectiveSet");
                });

            modelBuilder.Entity("Domain.Entities.DailyObjectiveSet", b =>
                {
                    b.HasOne("Domain.User.WorldPlayer", "WorldPlayer")
                        .WithOne("DailyObjectiveSet")
                        .HasForeignKey("Domain.Entities.DailyObjectiveSet", "WorldPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.IdeologyFocus", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("ActiveFocuses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User.WorldPlayer", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.Research", b =>
                {
                    b.HasOne("Domain.User.WorldPlayer", "WorldPlayer")
                        .WithMany("CompletedResearches")
                        .HasForeignKey("WorldPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.UnitDeployment", b =>
                {
                    b.HasOne("Domain.Entities.City", "OriginCity")
                        .WithMany("OriginUnitDeployments")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.City", "TargetCity")
                        .WithMany("TargetUnitDeployments")
                        .HasForeignKey("TargetCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User.WorldPlayer", "OwnerWorldPlayer")
                        .WithMany("UnitDeployments")
                        .HasForeignKey("WorldPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AppliesToCategory")
                                .HasColumnType("int");

                            b1.Property<bool>("ExcludeElite")
                                .HasColumnType("bit");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Tag")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("UnitDeploymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("UnitDeploymentId");

                            b1.ToTable("UnitDeploymentModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UnitDeploymentId");
                        });

                    b.Navigation("ModifiersInternal");

                    b.Navigation("OriginCity");

                    b.Navigation("OwnerWorldPlayer");

                    b.Navigation("TargetCity");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.Entities.UnitStack", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("UnitStacks")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.UnitDeployment", "UnitDeployment")
                        .WithMany("UnitStacks")
                        .HasForeignKey("UnitDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.WorldPlayer", "WorldPlayer")
                        .WithMany("UnitStacks")
                        .HasForeignKey("WorldPlayerId");

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AppliesToCategory")
                                .HasColumnType("int");

                            b1.Property<bool>("ExcludeElite")
                                .HasColumnType("bit");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Tag")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("UnitStackId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("UnitStackId");

                            b1.ToTable("UnitStackModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UnitStackId");
                        });

                    b.Navigation("City");

                    b.Navigation("ModifiersInternal");

                    b.Navigation("UnitDeployment");

                    b.Navigation("WorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.World", b =>
                {
                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AppliesToCategory")
                                .HasColumnType("int");

                            b1.Property<bool>("ExcludeElite")
                                .HasColumnType("bit");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Tag")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.Property<Guid>("WorldId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WorldId");

                            b1.ToTable("WorldModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorldId");
                        });

                    b.Navigation("ModifiersInternal");
                });

            modelBuilder.Entity("Domain.Entities.WorldIsland", b =>
                {
                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany("Islands")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.Entities.WorldIslandExoticResource", b =>
                {
                    b.HasOne("Domain.Entities.WorldIsland", "WorldIsland")
                        .WithMany("ExoticResources")
                        .HasForeignKey("WorldIslandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldIsland");
                });

            modelBuilder.Entity("Domain.Entities.WorldMapObject", b =>
                {
                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany("MapObjects")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.User.WorldPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Alliance", "Alliance")
                        .WithMany("Members")
                        .HasForeignKey("AllianceId");

                    b.HasOne("Domain.User.PlayerProfile", "PlayerProfile")
                        .WithMany("WorldPlayers")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AppliesToCategory")
                                .HasColumnType("int");

                            b1.Property<bool>("ExcludeElite")
                                .HasColumnType("bit");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Tag")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.Property<Guid>("WorldPlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WorldPlayerId");

                            b1.ToTable("PlayerModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorldPlayerId");
                        });

                    b.Navigation("Alliance");

                    b.Navigation("ModifiersInternal");

                    b.Navigation("PlayerProfile");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.Workers.BuildingJob", b =>
                {
                    b.HasOne("Domain.Entities.City", null)
                        .WithMany("BuildingQueue")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Alliance", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RelationsAsAllianceA");

                    b.Navigation("RelationsAsAllianceB");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("ActiveFocuses");

                    b.Navigation("BuildingQueue");

                    b.Navigation("Buildings");

                    b.Navigation("ExoticResources");

                    b.Navigation("OriginUnitDeployments");

                    b.Navigation("TargetUnitDeployments");

                    b.Navigation("UnitStacks");
                });

            modelBuilder.Entity("Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Domain.Entities.DailyObjectiveSet", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Domain.Entities.UnitDeployment", b =>
                {
                    b.Navigation("UnitStacks");
                });

            modelBuilder.Entity("Domain.Entities.World", b =>
                {
                    b.Navigation("Islands");

                    b.Navigation("MapObjects");
                });

            modelBuilder.Entity("Domain.Entities.WorldIsland", b =>
                {
                    b.Navigation("ExoticResources");
                });

            modelBuilder.Entity("Domain.User.PlayerProfile", b =>
                {
                    b.Navigation("WorldPlayers");
                });

            modelBuilder.Entity("Domain.User.WorldPlayer", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CompletedResearches");

                    b.Navigation("ConversationParticipants");

                    b.Navigation("DailyObjectiveSet");

                    b.Navigation("UnitDeployments");

                    b.Navigation("UnitStacks");
                });
#pragma warning restore 612, 618
        }
    }
}
