// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AllianceAlliance", b =>
                {
                    b.Property<Guid>("AlliancesAtWarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlliancesPactedId")
                        .HasColumnType("TEXT");

                    b.HasKey("AlliancesAtWarId", "AlliancesPactedId");

                    b.HasIndex("AlliancesPactedId");

                    b.ToTable("AllianceAlliance");
                });

            modelBuilder.Entity("Domain.Entities.Alliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alliances");
                });

            modelBuilder.Entity("Domain.Entities.BattleReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BattleReports");
                });

            modelBuilder.Entity("Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeOfUpgradeFinished")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOfUpgradeStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNPC")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Metal")
                        .HasColumnType("REAL");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Stone")
                        .HasColumnType("REAL");

                    b.Property<double>("Wood")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorldPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldPlayerId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.IdeologyFocus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeOfIdeologyFinished")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeOfIdeologyStarted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("IdeologyFocuses");
                });

            modelBuilder.Entity("Domain.Entities.Research", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResearchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorldPlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldPlayerId");

                    b.ToTable("Researches");
                });

            modelBuilder.Entity("Domain.Entities.UnitDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LootMetal")
                        .HasColumnType("REAL");

                    b.Property<double>("LootStone")
                        .HasColumnType("REAL");

                    b.Property<double>("LootWood")
                        .HasColumnType("REAL");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetCityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitDeploymentMovementStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitDeploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TargetCityId");

                    b.ToTable("UnitDeployments");
                });

            modelBuilder.Entity("Domain.Entities.UnitStack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("UnitStacks");
                });

            modelBuilder.Entity("Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XAxis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YAxis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("World");
                });

            modelBuilder.Entity("Domain.User.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Domain.User.WorldPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AllianceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AllianceRole")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ideology")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IdeologyFocusPoints")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiersThatAffectsThis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ResearchPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("Silver")
                        .HasColumnType("REAL");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldPlayers");
                });

            modelBuilder.Entity("Domain.Workers.Abstraction.BaseJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasDiscriminator<string>("JobType").HasValue("BaseJob");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Workers.BuildingJob", b =>
                {
                    b.HasBaseType("Domain.Workers.Abstraction.BaseJob");

                    b.Property<int>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CityId");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("Domain.Workers.RecruitmentJob", b =>
                {
                    b.HasBaseType("Domain.Workers.Abstraction.BaseJob");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTickTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("SecondsPerUnit")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.ToTable("Jobs", t =>
                        {
                            t.Property("CityId")
                                .HasColumnName("RecruitmentJob_CityId");
                        });

                    b.HasDiscriminator().HasValue("RecruitmentSpeed");
                });

            modelBuilder.Entity("Domain.Workers.ResearchJob", b =>
                {
                    b.HasBaseType("Domain.Workers.Abstraction.BaseJob");

                    b.Property<string>("ResearchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Research");
                });

            modelBuilder.Entity("AllianceAlliance", b =>
                {
                    b.HasOne("Domain.Entities.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AlliancesAtWarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AlliancesPactedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Alliance", b =>
                {
                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("AllianceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tag")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("AllianceId");

                            b1.ToTable("AllianceModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AllianceId");
                        });

                    b.Navigation("ModifiersInternal");
                });

            modelBuilder.Entity("Domain.Entities.Building", b =>
                {
                    b.HasOne("Domain.Entities.City", null)
                        .WithMany("Buildings")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId");

                    b.HasOne("Domain.User.WorldPlayer", "WorldPlayer")
                        .WithMany("Cities")
                        .HasForeignKey("WorldPlayerId");

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tag")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("CityId");

                            b1.ToTable("CityModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("ModifiersInternal");

                    b.Navigation("World");

                    b.Navigation("WorldPlayer");
                });

            modelBuilder.Entity("Domain.Entities.IdeologyFocus", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("ActiveFocuses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.Research", b =>
                {
                    b.HasOne("Domain.User.WorldPlayer", null)
                        .WithMany("CompletedResearches")
                        .HasForeignKey("WorldPlayerId");
                });

            modelBuilder.Entity("Domain.Entities.UnitDeployment", b =>
                {
                    b.HasOne("Domain.Entities.City", "OriginCity")
                        .WithMany("OriginUnitDeployments")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.City", "TargetCity")
                        .WithMany("TargetUnitDeployments")
                        .HasForeignKey("TargetCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tag")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("UnitDeploymentId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("UnitDeploymentId");

                            b1.ToTable("UnitDeploymentModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UnitDeploymentId");
                        });

                    b.Navigation("ModifiersInternal");

                    b.Navigation("OriginCity");

                    b.Navigation("TargetCity");
                });

            modelBuilder.Entity("Domain.Entities.UnitStack", b =>
                {
                    b.HasOne("Domain.Entities.City", null)
                        .WithMany("UnitStacks")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tag")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("UnitStackId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("UnitStackId");

                            b1.ToTable("UnitStackModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UnitStackId");
                        });

                    b.Navigation("ModifiersInternal");
                });

            modelBuilder.Entity("Domain.Entities.World", b =>
                {
                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tag")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.Property<Guid>("WorldId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("WorldId");

                            b1.ToTable("WorldModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorldId");
                        });

                    b.Navigation("ModifiersInternal");
                });

            modelBuilder.Entity("Domain.User.WorldPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Alliance", "Alliance")
                        .WithMany("Members")
                        .HasForeignKey("AllianceId");

                    b.HasOne("Domain.User.PlayerProfile", "PlayerProfile")
                        .WithMany("WorldPlayers")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Entities.Modifier", "ModifiersInternal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tag")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.Property<Guid>("WorldPlayerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("WorldPlayerId");

                            b1.ToTable("PlayerModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorldPlayerId");
                        });

                    b.Navigation("Alliance");

                    b.Navigation("ModifiersInternal");

                    b.Navigation("PlayerProfile");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Domain.Workers.BuildingJob", b =>
                {
                    b.HasOne("Domain.Entities.City", null)
                        .WithMany("BuildingQueue")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Alliance", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("ActiveFocuses");

                    b.Navigation("BuildingQueue");

                    b.Navigation("Buildings");

                    b.Navigation("OriginUnitDeployments");

                    b.Navigation("TargetUnitDeployments");

                    b.Navigation("UnitStacks");
                });

            modelBuilder.Entity("Domain.User.PlayerProfile", b =>
                {
                    b.Navigation("WorldPlayers");
                });

            modelBuilder.Entity("Domain.User.WorldPlayer", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CompletedResearches");
                });
#pragma warning restore 612, 618
        }
    }
}
